var ConfigMockData = {
    config: {
        transparent_redirect_environment_key: 'XXXXXXXXXX',
        id: 1024,
        is_sandbox: true,
        sandbox_catchall_email: 'david.king@subscribepro.com',
        ecommerce_platform_connection_type: 'magento_1_soap_api',
        magento_url: 'https://fluid-m1.subscribepro.com/',
        magento_admin_url: 'https://fluid-m1.subscribepro.com/admin/',
        magento_store_code: 'default',
        magento_api_url: 'https://fluid-m1.subscribepro.com/index.php/api/soap',
        magento_api_username: 'fluid-sp',
        magento2_api_clean_quote: false,
        payment_vault: 'Subscribe Pro Sandbox',
        dual_vault_mode: 'disabled',
        enable_transaction_routing_rules: false,
        magento_payment_method: 'subscribe_pro',
        authorize_net_duplicate_window: 120,
        automatic_order_generation: true,
        order_generation_time: '08:00:00',
        fulfillment_threshold_days: 3,
        default_min_qty: 1,
        default_max_qty: 9,
        default_discount: 0.2,
        default_intervals: [
            'Every 2 Months',
            'Monthly',
            'Weekly'
        ],
        email_template_translate_with_magento_store_code: false,
        from_email: 'david.king@subscribepro.com',
        from_email_name: 'David King',
        from_email_use_dkim_domain: true,
        store_name: 'Fluid Magento 1 Demo',
        email_logo_filename: '58aefa0a1c01d_subscribepro-logo.png',
        customer_service_email: 'david.king@subscribepro.com',
        customer_service_phone: '123-456-7890',
        email_template_disable_subscription_created: false,
        email_template_disable_subscription_updated: false,
        email_template_disable_subscription_cancelled: false,
        email_template_disable_subscription_order_failed: false,
        email_template_disable_upcoming_subscription: false,
        email_template_disable_expiring_card: true,
        upcoming_subscription_email_days_ahead: 2,
        upcoming_subscription_email_time: '10:00:00',
        expiring_card_email_days_ahead: 14,
        expiring_card_email_time: '00:00:00',
        trial_conversion_email_time: '00:00:00',
        subscription_order_failed_email_first_time_only: false,
        order_generation_subscription_grouping_mode: 'standard',
        order_generation_shipping_method_mode: 'always_apply_default',
        order_generation_free_payment_mode: 'never_use_free',
        default_magento_shipping_method_code: 'flatrate_flatrate',
        order_generation_store_mode: 'use_default_store',
        order_generation_api_mode: 'use_standard_magento',
        order_generation_use_reward_points: false,
        order_generation_max_reward_points: 0,
        locale: 'en_US',
        timezone: 'America/New_York',
        currency: 'USD',
        created: '2017-02-23T15:01:25+0000',
        updated: '2017-02-23T15:51:50+0000'
    }
};

module.exports = ConfigMockData;
