
import FormField = require('dw/web/FormField')
import FormGroup = require('dw/web/FormGroup');
import FormAction = require('dw/web/FormAction');
// autogeneratedfile

/** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/preferences.xml#2)*/
declare class FormPreferences extends FormGroup {
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/preferences.xml#3) */
	interestApparel : FormField<boolean>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/preferences.xml#4) */
	interestElectronics : FormField<boolean>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/preferences.xml#5) */
	newsletter : FormField<boolean>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/preferences.xml#7) */
	apply : FormAction
}
/** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#2)*/
declare class FormSrvnewsletter extends FormGroup {
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#3) */
	fname : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#4) */
	lname : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#5) */
	email : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#11) */
	promo : FormField<boolean>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#12) */
	subscribe : FormAction
}
/** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#2)*/
declare class FormAddress extends FormGroup {
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#4) */
	addressId : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#6) */
	firstName : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#8) */
	lastName : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#10) */
	address1 : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#12) */
	address2 : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#14) */
	city : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#18) */
	postalCode : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#26) */
	country : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#34) */
	states : FormStates
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#37) */
	phone : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#45) */
	secondaryPhone : FormField<string>
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#55) */
	apply : FormAction
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#56) */
	remove : FormAction
}

declare global {
interface SFCCForms {
	preferences: FormPreferences
	srvnewsletter: FormSrvnewsletter
	address: FormAddress
}
}


/****** SRFA *******/

interface SfraAction {
    description: string | null;
    label: string | null;
    submitted: boolean | null;
    triggered: boolean | null;
    formType: string;
}

interface SfraFiledOptions {
	checked: boolean,
	htmlValue: string,
	label: string,
	id: string,
	selected: boolean,
	value: string
}

interface SfraFieldBoolean {
	checked: boolean;
	selected: boolean;
}

interface SfraFieldString {
	maxLength: number;
	minLength: number;
	regEx: string
}

interface SfraFieldInteger {
	maxValue: number;
	minValue: number;
}

interface SfraField<T> {
	valid: boolean;
	error: string | null
	readonly attributes: string;
	value: T;
	options: SfraFiledOptions[];
	selectedOption: string;
	formType: string;

	htmlValue: string,
	mandatory: boolean,
	dynamicHtmlName: string
	htmlName: string
}

interface SfraFormBase<T> {
	clear() : void;
	copyFrom(src: object): void;
	toObject(): any;
	valid: boolean;
	base: T
	htmlName: string,
	dynamicHtmlName: string,
	error: string | null,
	attributes: string,
	formType: 'formGroup'
}
/** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/preferences.xml#2)*/
interface SfraFormPreferences extends SfraFormBase<FormPreferences> {
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/preferences.xml#3) */
	interestApparel : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/preferences.xml#4) */
	interestElectronics : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/preferences.xml#5) */
	newsletter : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/preferences.xml#7) */
	apply : SfraAction
}
/** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#2)*/
interface SfraFormSrvnewsletter extends SfraFormBase<FormSrvnewsletter> {
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#3) */
	fname : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#4) */
	lname : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#5) */
	email : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#11) */
	promo : SfraField<boolean> & SfraFieldBoolean
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/srvnewsletter.xml#12) */
	subscribe : SfraAction
}
/** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#2)*/
interface SfraFormAddress extends SfraFormBase<FormAddress> {
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#4) */
	addressId : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#6) */
	firstName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#8) */
	lastName : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#10) */
	address1 : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#12) */
	address2 : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#14) */
	city : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#18) */
	postalCode : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#26) */
	country : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#34) */
	states : SfraFormStates
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#37) */
	phone : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#45) */
	secondaryPhone : SfraField<string> & SfraFieldString
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#55) */
	apply : SfraAction
	 /** @source [definition](file:/Users/sumitkumawat/sumit/Commerce/Client/cartridges/app_custom_sumit/cartridge/forms/default/address.xml#56) */
	remove : SfraAction
}

declare global {
interface SFRAServerForms {
	getForm(name: 'preferences'): SfraFormPreferences
	getForm(name: 'srvnewsletter'): SfraFormSrvnewsletter
	getForm(name: 'address'): SfraFormAddress
}
}

declare global {
interface SRFAForms {
	preferences: SfraFormPreferences
	srvnewsletter: SfraFormSrvnewsletter
	address: SfraFormAddress
}
}